
#pragma once

#include "ofMain.h"

enum AnimationEngineMode
{
    ANIMATION_MODE_EDIT,
    ANIMATION_MODE_VIEW,
    ANIMATION_MODE_PLAY,
};

enum AnimationPlayState
{
    ANIMATION_PLAY_STATE_PLAY,
    ANIMATION_PLAY_STATE_PAUSED,
    ANIMATION_PLAY_STATE_STOPPED
};
enum AnimationLoopState
{
    ANIMATION_LOOP_STATE_NONE,
    ANIMATION_LOOP_STATE_FORWARD,
    ANIMATION_LOOP_STATE_BACKWARD
};
enum AnimtionFinishState
{
    ANIMATION_FINISH_STATE_STATIC,
    ANIMATION_FINISH_STATE_DELETE,
    ANIMATION_FINISH_STATE_DELETE_FADE,
    //TODO add more
};
///EnumDefinition_AnimationType_Movement_MovementType_Multiply
enum AnimationType
{
    ANIMATION_TYPE_IMAGE_SINGLE_STILL,
    ANIMATION_TYPE_IMAGE_SINGLE_MOVING,
    ANIMATION_TYPE_IMAGE_SINGLE_MOVING_MULTIPLY,
    //ANIMATION_TYPE_IMAGE_SINGLE_MOVING_LOOP,
    //ANIMATION_TYPE_IMAGE_SINGLE_MOVING_LOOP_BACKWARD,
    ANIMATION_TYPE_IMAGE_SINGLE_MOVING_BEZIER,
    ANIMATION_TYPE_IMAGE_SINGLE_MOVING_BEZIER_MULTIPLY,
    //ANIMATION_TYPE_IMAGE_SINGLE_MOVING_BEZIER_LOOP,
    //ANIMATION_TYPE_IMAGE_SINGLE_MOVING_BEZIER_LOOP_BACKWARD,
    ANIMATION_TYPE_IMAGE_MULTIPLY_STILL,
    ANIMATION_TYPE_IMAGE_MULTIPLY_MOVING,
    ANIMATION_TYPE_IMAGE_MULTIPLY_MOVING_MULTIPLY,
    ANIMATION_TYPE_IMAGE_MULTIPLY_MOVING_BEZIER,
    ANIMATION_TYPE_IMAGE_MULTIPLY_MOVING_BEZIER_MULTIPLY,
    
    //To add
    ANIMATION_TYPE_MODEL_STILL,
    ANIMATION_TYPE_MODEL_MOVING,
    
    ANIMATION_TYPE_PARTICLE_STILL,
    ANIMATION_TYPE_PARTICLE_MOVING
};

enum AnimationClass
{
    ANIMATION_CLASS_BASE,
    ANIMATION_CLASS_MOVING,
    ANIMATION_CLASS_MOVING_BEZIER
};

enum AnimationScreenType
{
    ANIMATION_SCREEN_TYPE_STILL,
    ANIMATION_SCREEN_TYPE_MOVING,
    ANIMATION_SCREEN_TYPE_ZOOM
};

enum AnimationManagerUtilImage
{
    ANIMATION_MANAGER_UTIL_IMAGE_POINT = 0
};

enum AnimationManagerGUIWindow
{
    ANIMATION_MANAGER_GUI_WINDOW_MODE,
    ANIMATION_MANAGER_GUI_WINDOW_OBJECT,
    ANIMATION_MANAGER_GUI_WINDOW_OBJECT_IMAGE_DURATION,
    ANIMATION_MANAGER_GUI_WINDOW_PLAY
};
struct AnimationManagerIndex
{
    int index;
    AnimationClass animationClass;
    int drawIndex;
};

